import duckdb as db
import json
import re

# tmp, needs to come from argv
duckdb_source_repo = "..."

def main():
    docs_map = {
        "math": "docs/sql/functions/numeric.md",
    }
    splitline = "## Numeric Functions"
    for module, doc_file in docs_map.items():
        update_doc(module, doc_file, splitline)


def update_doc(module, doc_file, splitline):
    function_data = get_function_data(module)
    with open(doc_file, "r") as f:
        doc_text = f.read()
    if splitline not in doc_text:
        print(f"ref split ({splitline}) not found in file " + doc_file)
        exit(1)
    else:
        doc_text_splitted = doc_text.rsplit(splitline, 1)
        doc_text_new = (
            doc_text_splitted[0]
            + splitline
            + text_above_table(doc_text_splitted[1])
            + "\n\n<!-- This section is generated by scripts/generate_sql_function_docs.py -->\n\n"
            + generate_docs_table(function_data)
            + generate_docs_records(function_data)
        )
        with open(doc_file, "w+") as f:
            f.write(doc_text_new)

def get_function_data(module):
    functions_json_file = (
        duckdb_source_repo + f"src/core_functions/scalar/{module}/functions.json"
    )
    query_aliases_from_json = f'''
    create table
        aliases as
    select
        list_append (aliases, name) as aliases
    from
        (
            select
                name,
                aliases
            from
                read_json ('{functions_json_file}')
        );
    '''

    query_function_data = f'''
    select distinct
        function_name,
        parameters,
        description,
        example,
        list_sort (filter (aliases, x -> x != function_name)) as aliases
    from
        duckdb_functions ()
        join aliases on list_contains (aliases, function_name)
    order by
        function_name;
    '''
    db.sql(query_aliases_from_json)
    return (db.sql(query_function_data).fetchall())


def text_above_table(text):
    regex_start_table = r"\n *\|.*\|*\n"
    return re.split(pattern=regex_start_table, string=text, maxsplit=1)[0].rstrip()


def generate_docs_table(function_data):
    res = "| Name | Description |\n|:--|:-------|\n"
    for func in function_data:
        name, params, description, _, _ = func
        params = list(map(lambda a: a.strip(), params))
        res += f"| [`{name}({",".join(params)})`](#{name}{"-".join(params)}) | {description} |\n"
    return res


def generate_docs_records(function_data):
    return "dummy2\n"


if __name__ == "__main__":
    main()
