import duckdb as db
import json
import re

# tmp, needs to come from argv
duckdb_source_repo = "..."

def main():
    docs_map = {
        "math": "docs/sql/functions/numeric.md",
    }
    splitline = "## Numeric Functions"
    for module, doc_file in docs_map.items():
        update_doc(module, doc_file, splitline)


def update_doc(module, doc_file, splitline):
    function_file = (
        duckdb_source_repo + f"src/core_functions/scalar/{module}/functions.json"
    )

    with open(function_file) as f:
        data = json.load(f)
    with open(doc_file) as f:
        doc_text = f.read()
    if splitline not in doc_text:
        print(f"ref split ({splitline}) not found in file " + doc_file)
        exit(1)
    else:
        doc_text_splitted = doc_text.rsplit(splitline, 1)

    doc_text_new = (
        doc_text_splitted[0]
        + splitline
        + text_above_table(doc_text_splitted[1])
        + "\n\n<!-- This section is generated by scripts/generate_sql_function_docs.py -->\n\n"
        + generate_docs_table()
        + generate_docs_records()
    )

    with open(doc_file, "w+") as f:
        f.write(doc_text_new)


def text_above_table(text):
    regex_start_table = r"\n *\|.*\|*\n"
    return re.split(pattern=regex_start_table, string=text, maxsplit=1)[0].rstrip()


def generate_docs_table():
    return "dummy1\n"


def generate_docs_records():
    return "dummy2\n"


if __name__ == "__main__":
    main()
