import duckdb as db
import json
import re

# tmp, needs to come from argv
duckdb_source_repo = "..."

def main():
    docs_map = {
        "math": "docs/sql/functions/numeric.md",
    }
    for module, doc_file in docs_map.items():
        update_doc(module, doc_file)


def update_doc(module, doc_file):
    function_data = get_function_data(module)
    startline = "<!-- Start of section generated by scripts/generate_sql_function_docs.py -->\n"
    endline = "<!-- End of section generated by scripts/generate_sql_function_docs.py -->\n"
    with open(doc_file, "r") as f:
        doc_text = f.read()
    if startline not in doc_text or endline not in doc_text:
        print(f"doc generation failed, start or end line is missing in file " + doc_file)
        exit(1)
    else:
        split_start = doc_text.rsplit(startline, 1)
        split_end = doc_text.rsplit(endline, 1)
        doc_text_new = (
            split_start[0]
            + startline
            + generate_docs_table(function_data)
            + generate_docs_records(function_data)
            + endline
            + split_end[1]
        )
        with open(doc_file, "w+") as f:
            f.write(doc_text_new)


def get_function_data(module):
    functions_json_file = (
        duckdb_source_repo + f"src/core_functions/scalar/{module}/functions.json"
    )
    query_aliases_from_json = f'''
    create table
        aliases as
    select
        list_append (aliases, name) as aliases
    from
        (
            select
                name,
                aliases
            from
                read_json ('{functions_json_file}')
        );
    '''

    query_function_data = f'''
    select distinct
        function_name,
        parameters,
        description,
        example,
        list_sort (filter (aliases, x -> x != function_name)) as aliases
    from
        duckdb_functions ()
        join aliases on list_contains (aliases, function_name)
    order by
        function_name;
    '''
    db.sql(query_aliases_from_json)
    return (db.sql(query_function_data).fetchall())


def generate_docs_table(function_data):
    res = "| Name | Description |\n|:--|:-------|\n"
    for func in function_data:
        name, params, description, _, _ = func
        params = list(map(lambda a: a.strip(), params))
        res += f"| [`{name}({", ".join(params)})`](#{name.lstrip('@*!^')}{"-".join(params)}) | {description} |\n"
    return res


def generate_docs_records(function_data):
    res = "\n\n"
    for func in function_data:
        name, params, description, example, alias = func
        params = list(map(lambda a: a.strip(), params))
        res += f"### `{name}({", ".join(params)})`\n\n"
        res += "<div class=\"nostroke_table\"></div>\n\n"
        res += f"| **Description** | {description} |\n"
        res += f"| **Example** | `{example}` |\n"
        res += f"| **Result** | `{db.sql(f"select {example}").fetchone()[0]}` |\n"
        if alias:
            res += f"| **Alias** | {", ".join(alias)} |\n"
        res += "\n"
    return res


if __name__ == "__main__":
    main()
